"""empty message

Revision ID: 00746c46ea63
Revises: 78c05acad026
Create Date: 2024-10-05 21:04:49.041385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00746c46ea63'
down_revision = '78c05acad026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subregions',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('region_id', sa.SmallInteger(), nullable=True),
    sa.Column('wikiDataId', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.SmallInteger(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    op.drop_table('subregions')
    # ### end Alembic commands ###
