"""empty message

Revision ID: 00ead6611b23
Revises: 00746c46ea63
Create Date: 2024-10-05 21:07:56.614817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00ead6611b23'
down_revision = '00746c46ea63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('country_id', sa.SmallInteger(), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('state_id',
               existing_type=mysql.BIGINT(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
        batch_op.alter_column('country_id',
               existing_type=mysql.BIGINT(),
               type_=sa.SmallInteger(),
               existing_nullable=True)

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('region_id',
               existing_type=mysql.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
        batch_op.alter_column('subregion_id',
               existing_type=mysql.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('subregion_id',
               existing_type=sa.SmallInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('region_id',
               existing_type=sa.SmallInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.SmallInteger(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('country_id',
               existing_type=sa.SmallInteger(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('state_id',
               existing_type=sa.SmallInteger(),
               type_=mysql.BIGINT(),
               existing_nullable=True)

    op.drop_table('states')
    # ### end Alembic commands ###
