"""empty message

Revision ID: 27cd35aa97de
Revises: c9109b4c8475
Create Date: 2024-10-05 20:43:22.778085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27cd35aa97de'
down_revision = 'c9109b4c8475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('state_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('country_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=8),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=mysql.DECIMAL(precision=11, scale=8),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=mysql.DECIMAL(precision=11, scale=8),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=8),
               nullable=False)
        batch_op.alter_column('country_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
        batch_op.alter_column('state_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
