"""empty message

Revision ID: 72a8034c8cf2
Revises: 55c26d593788
Create Date: 2024-10-06 16:39:39.794043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a8034c8cf2'
down_revision = '55c26d593788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('state_id', sa.SmallInteger(), nullable=True),
    sa.Column('country_id', sa.SmallInteger(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('wikiDataId', sa.String(length=255), nullable=True),
    sa.Column('population', sa.BigInteger(), nullable=True),
    sa.Column('elevation_in_meter', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    # ### end Alembic commands ###
